# Generated by Django 2.2.3 on 2019-09-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='pic',
            new_name='superhero',
        ),
    ]
