# Generated by Django 2.2.3 on 2019-09-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190916_2054'),
        ('main_app', '0003_auto_20190916_2234'),
    ]

    operations = [
    ]
