# Generated by Django 2.2.3 on 2019-10-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_superhero_user'),
        ('main_app', '0004_merge_20190917_1700'),
    ]

    operations = [
    ]
